import type { MetadataRoute } from "next";
import {
  SITE_URL,
  LIVE_CALCULATORS,
  LIVE_ARTICLES,
  CATEGORIES,
} from "@/lib/site";
import { BLOG_POSTS } from "@/lib/blog";

// Hierarchical sitemap.
//
//   /sitemap.xml                       (sitemap index — auto-generated by Next.js)
//   ├── /sitemap/main.xml              home + about + blog index + blog posts + every
//   │                                  category landing page
//   ├── /sitemap/finance.xml           every live finance calculator
//   ├── /sitemap/math.xml              every live math calculator
//   ├── /sitemap/stats.xml             every live statistics calculator
//   ├── /sitemap/health.xml            every live health calculator
//   ├── /sitemap/construction.xml      every live construction calculator
//   ├── /sitemap/education.xml         every live education calculator
//   ├── /sitemap/betting.xml           every live betting calculator
//   ├── /sitemap/payroll.xml           paycheck-calculator + 50 state pages
//   ├── /sitemap/pets.xml              every live pets calculator
//   └── /sitemap/articles.xml          every live article/guide (currently empty)
//
// This structure tells Google + Bing how the catalog is organised, lets us
// submit each topical cluster to GSC independently, and gives LLMs that
// fetch the sitemap a clean topical map of the site.

const CATEGORY_IDS = Object.keys(CATEGORIES);

export async function generateSitemaps() {
  return [{ id: "main" }, ...CATEGORY_IDS.map((id) => ({ id }))];
}

export default async function sitemap({
  id,
}: {
  id: Promise<string>;
}): Promise<MetadataRoute.Sitemap> {
  const sid = await id;
  const now = new Date();

  if (sid === "main") {
    const root: MetadataRoute.Sitemap = [
      { url: `${SITE_URL}/`, lastModified: now, changeFrequency: "weekly", priority: 1.0 },
      { url: `${SITE_URL}/about`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
      { url: `${SITE_URL}/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    ];

    const blog: MetadataRoute.Sitemap = BLOG_POSTS.map((p) => ({
      url: `${SITE_URL}/blog/${p.slug}`,
      lastModified: new Date(p.dateModified),
      changeFrequency: "monthly" as const,
      priority: 0.7,
    }));

    // Every category that has at least one live calculator or article gets a
    // landing page in the main sitemap.
    const liveCategories = new Set([
      ...LIVE_CALCULATORS.map((c) => c.category),
      ...LIVE_ARTICLES.map((a) => a.category),
    ]);
    const categories: MetadataRoute.Sitemap = [...liveCategories]
      .filter((c) => CATEGORIES[c])
      .map((c) => ({
        url: `${SITE_URL}/${c}`,
        lastModified: now,
        changeFrequency: "monthly" as const,
        priority: 0.8,
      }));

    return [...root, ...categories, ...blog];
  }

  // Unknown category id — return empty rather than 404 so the sitemap index
  // stays a clean schema even if the catalog changes shape.
  if (!CATEGORIES[sid]) return [];

  const calcs: MetadataRoute.Sitemap = LIVE_CALCULATORS.filter(
    (c) => c.category === sid,
  ).map((c) => ({
    url: `${SITE_URL}/${c.slug}`,
    lastModified: now,
    changeFrequency: "monthly",
    priority: 0.8,
  }));

  // Programmatic state variants (paycheck-calculator/<state>) live with their
  // parent calculator's category.
  const stateRoutes: MetadataRoute.Sitemap = LIVE_CALCULATORS.filter(
    (c) => c.category === sid && c.programmatic?.type === "us-state",
  ).flatMap((c) =>
    c.programmatic!.states.map((s) => ({
      url: `${SITE_URL}/${c.slug}/${s}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    })),
  );

  const articles: MetadataRoute.Sitemap = LIVE_ARTICLES.filter(
    (a) => a.category === sid,
  ).map((a) => ({
    url: `${SITE_URL}/${a.slug}`,
    lastModified: now,
    changeFrequency: "monthly",
    priority: 0.7,
  }));

  return [...calcs, ...stateRoutes, ...articles];
}
